name: fbias
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.8
  - pip
  - numpy>=1.20
  - scipy=1.7.1
  - pytorch=1.9.1
  - torchvision
  - cudatoolkit=11.1
  - tqdm=4.62.2
  - matplotlib=3.4.2
  - pyyaml=5.3.1
  - imageio=2.9.0
  - tensorboardX
  - pip:
    - imageio-ffmpeg==0.4.3
