data:
  root: data/toyset64_100
  subset: 10
model:
  class_name: models.PGGANGenerator
  z_dim: 64
  divide_channels_by: 8
  upsampling_mode: bilinear
training:
  nepochs: 100000
  print_every: 1000
  eval_every: 1000
  save_every: 10000