data:
  root: data/toyset64_100
  resolution: 64
  subset:
model:
training:
  batch_size: 10
  nworkers: 0
  monitoring: tensorboard
  nepochs: 500
  print_every: 10
  eval_every: 10
  save_every: 10
  lr: 0.001
  criterion:
    class_name: torch.nn.MSELoss
    weight:
  model_file: model.pt
  seed: 0
